# Generated by Django 3.2.8 on 2021-10-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('PlayerId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('CurrentClub', models.CharField(max_length=20)),
                ('nationallity', models.CharField(max_length=20)),
                ('DateOfBirth', models.DateField()),
                ('Position', models.CharField(max_length=20)),
                ('LastModified', models.DateField()),
            ],
        ),
    ]
