# Generated by Django 3.2.8 on 2021-10-20 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayersApp', '0002_alter_player_lastmodified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='LastModified',
            field=models.DateField(default=datetime.datetime(2021, 10, 20, 16, 7, 27, 778252)),
        ),
    ]
