# Generated by Django 3.2.8 on 2021-10-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayersApp', '0003_alter_player_lastmodified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='LastModified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
